package com.shop.store.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

import com.shop.store.model.CartView;

/**
 * Legacy client-supplied snapshot; saving it does not debit inventory or publish an event.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "orders")
public class Order {
    /** Identifier supplied by the existing client rather than generated by the server. */
    @Id
    private Long id;

    /** Client timestamp retained by the transitional API. */
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    /** Client total; authoritative submission calculation arrives in task 6. */
    @Column(name = "order_sum")
    private BigDecimal orderSum;

    /** JSON snapshot accepted from the legacy HTML client. */
    @Column(columnDefinition = "jsonb")
    @JdbcTypeCode(SqlTypes.JSON)
    private List<CartView> items;
}
