spring:
  application:
    name: tariffs-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:34567/tariffs_db}
    username: ${DB_USER:tariffs_app}
    password: ${DB_PASSWORD:tariffs_local}
    hikari:
      connection-timeout: 2000
      validation-timeout: 1000
      data-source-properties:
        socketTimeout: 5
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    baseline-on-migrate: false
    clean-disabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 500ms
      connect-timeout: 500ms
server:
  port: ${SERVER_PORT:6790}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
      group:
        readiness:
          include: readinessState,db
