-- Local development credentials only. Each application owns exactly one database.
CREATE ROLE store_app LOGIN PASSWORD 'store_local' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE tariffs_app LOGIN PASSWORD 'tariffs_local' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE ROLE warehouse_app LOGIN PASSWORD 'warehouse_local' NOSUPERUSER NOCREATEDB NOCREATEROLE;
CREATE DATABASE store_db OWNER store_app;
CREATE DATABASE tariffs_db OWNER tariffs_app;
CREATE DATABASE warehouse_db OWNER warehouse_app;
REVOKE CONNECT ON DATABASE store_db FROM PUBLIC;
REVOKE CONNECT ON DATABASE tariffs_db FROM PUBLIC;
REVOKE CONNECT ON DATABASE warehouse_db FROM PUBLIC;
GRANT CONNECT ON DATABASE store_db TO store_app;
GRANT CONNECT ON DATABASE tariffs_db TO tariffs_app;
GRANT CONNECT ON DATABASE warehouse_db TO warehouse_app;
REVOKE CONNECT ON DATABASE bootstrap_db FROM PUBLIC;
REVOKE CONNECT ON DATABASE postgres FROM PUBLIC;
REVOKE CONNECT ON DATABASE template1 FROM PUBLIC;
