spring:
  application:
    name: warehouse-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:34567/warehouse_db}
    username: ${DB_USER:warehouse_app}
    password: ${DB_PASSWORD:warehouse_local}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    baseline-on-migrate: false
    clean-disabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
server:
  port: ${SERVER_PORT:6791}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
